### PR TITLE
Updated link to Oracle instant client download page.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Review by pope1ni — APPROVED** [review]
LGTM. (Test failures are unrelated. Due to issues with GeoIP stuff.)

**Comment by felixxm** [comment]
It's really old :smile: We should be able to download them automatically from GitHub, e.g. https://raw.githubusercontent.com/pwnlabs/oracle-instantclient/master/oracle-instantclient19.6-basiclite-19.6.0.0.0-1.x86_64.rpm. I will prepare a new PR.

**Comment by pope1ni** [comment]
Heh. Fair enough. Are there any licensing implications in doing this though? Oracle are typically very unfriendly in that regard.

Also, https://github.com/pwnlabs shows it has been moved to https://github.com/f00b4r.

So I guess you'd want to update the link... Although their [`README`](https://github.com/f00b4r/oracle-instantclient#readme) is outdated! 🤷🏻‍♂️

**Comment by felixxm** [comment]
It looks that currently we can even use links from the Oracle download page. They no longer require to be logged in, e.g.
https://download.oracle.com/otn_software/linux/instantclient/1911000/oracle-instantclient19.11-basic-19.11.0.0.0-1.x86_64.rpm

**Comment by pope1ni** [comment]
Ooh. That's progress! \o/

**Pull request closed without merging**
