### PR TITLE
Added Python 3.8 testing.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
We have to wait for a `python:3.8-slim` image.

**Comment by orf** [comment]
I guess we need to wait for Pillow to release a Python 3.8 wheel? It's using `https://files.pythonhosted.org/packages/87/dc/7597336c48796d4a836007460148b7baf7f278ad42b73d49047eb0e8194c/Pillow-6.2.0.tar.gz`, which fails because it's missing a bunch of headers.

Or should we install those via `apt` as well?

**Comment by pope1ni** [comment]
[Pillow 6.2.1](https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#621-2019-10-21) is now available with support for Python 3.8 and [`python:3.8-slim`](https://hub.docker.com/_/python) is also available.

(As an aside, PostgreSQL 12 and PostGIS 3 are also now available.)

**Comment by felixxm** [comment]
@orf Thanks, I will check MariaDB failures tomorrow.

**Pull request merged**
